### PR TITLE
Updates for latest Ruby versions, removes support for EOLed Ruby versions

### PR DESCRIPTION
**Pull request by alindeman**
Supercedes and closes #13

### CODE REVIEW

**Comment by alindeman** [comment]
@matsubo @davidbegin How do you feel about these changes? I wanted to be a little more conservative with some of the changes in #13, but I think this keeps the major ones. Thank you for being involved. See anything wrong here?

**Comment by matsubo** [comment]
@alindeman Yeah. seems OK. If you go more conservative, I suggest trying this. https://github.com/alindeman/zonebie/pull/13#issuecomment-190113389

Supporting only over Ruby 2.0 is too aggressive. I think.

**Comment by davidbegin** [comment]
First off, thanks so much for making Zonebie! I use it in my tests suites at work,
and it has uncovered countless bugs.

So there are 3 types of changes in this PR:
* dropping support for ruby 1.9.3 and below
* general refactorings
* updates to specs to use newer RSpec syntax

To clarify, the changes I was looking at making were the last 2 points.
I did not have any idea to drop support for <= 1.9.3.

So the general refactors in the Zonebie module and the spec updates all look good to me.
pretty much exactly what I was looking at doing.

As for dropping support, the changes look correct to me, but it might be better to have someone
more familiar with the codebase take a look. And also this means that the version should bumped.
And for dropping support I usually do a major version bump (does that mean Zonebie is going 1.0!?).

**Comment by alindeman** [comment]
Thanks all. Zonebie 0.6.0 has been released.

**Pull request merged**
