### PR TITLE
Feature/test latest ruby

### PR DESCRIPTION
**Pull request by matsubo**
This gem is valuable for me so I updated to follow ruby gem trend.
- Removed old ruby version support
- Refactoring according to rubocop
- setup code climate coverage test
- Please update the version number from 0.5.1 described in following the files.
  - https://github.com/matsubo/zonebie/blob/feature/test-latest-ruby/lib/zonebie/version.rb
  - https://github.com/matsubo/zonebie/blob/feature/test-latest-ruby/zonebie.gemspec

### CODE REVIEW

**Comment by matsubo** [comment]
@alindeman Any suggestions?

**Comment by alindeman** [comment]
I'll try to review this over the weekend. Thank you for your contribution!

**Comment by metaps-koike** [comment]
:+1:

**Comment by conf** [comment]
Failed Travis builds on old ruby versions is a known issue, take a look here: https://github.com/travis-ci/travis-ci/issues/3531 (tl;dr: old rubies come with old bundler).

The fix is quite easy, just update your bundler in `before_install` hook in `.travis.yml`, like this: 

```yml
before_install: 
  - gem update --system
  - gem install bundler
```

**Comment by davidbegin** [comment]
Quite a few of these changes I was already thinking of fixing. So :+1:

**Pull request closed without merging**
