### PR TITLE
Test against multiple versions of ActiveSupport

### LINKED ISSUE #1: Add Gemfiles for each of Rails 2.3, 3.0, 3.1 and 3.2
And make them run against Travis: http://about.travis-ci.org/docs/user/languages/ruby/ "Custom Bundler arguments and Gemfile locations"

### PR DESCRIPTION
**Pull request by odlp**
On Travis run tests with ActiveSupport versions `3.0`, `4.1`, `4.2`, `5.0`, `5.1`.

Fixes #1 

---

## Skipping ActiveSupport 4.0.x

We can't use Appraisal to test ActiveSupport 4.0 because this requires `tzinfo` gem at ~> 0.3.37, but the gemspec requires `tzinfo` as a dev dependency at >= 1.2.2, which leads to a conflict.

active-support-4 0
https://rubygems.org/gems/activesupport/versions/4.0.13

Other ActiveSupport versions can be tested:
- ActiveSupport 3.x didn't require `tzinfo`
- ActiveSupport >= 4.1 needs `tzinfo ~> 1.1` which can be satisfied

### CODE REVIEW

**Comment by odlp** [comment]
The `rbx-2` builds are failing, this might the following TravisCI issue:
https://github.com/travis-ci/travis-ci/issues/5294

Q: Should we remove Rubinius from the build? Several other projects seem to be removing it according to that issue.

---

The `jruby-19mode` builds are failing because:

```
Bundler could not find compatible versions for gem "ruby"

In Gemfile:
    ruby java
    zonebie java was resolved to 0.6.1, which depends on
      ruby (>= 2.0.0) java
```

If `zonebie` requires `ruby >= 2.0.0` then I think we can't use `jruby-19mode`. 

Q2: Shall we bump the `jruby` version to `9.x` (which is similar to Ruby 2.2).

---

Q3: If we rebuild `master` - is it currently green? The last build was over a year ago.

**Comment by odlp** [comment]
Other gems, like `vcr` and `redcarpet`, now allow `rbx-2` to fail on Travis:

https://github.com/vcr/vcr/commit/3fe3166cb941bcb8b9a80aec35b6d372339a50d6
https://github.com/ejholmes/restforce/commit/9cde3be3bfff7a8778c9e07dd0431a5c048e7f55

**Comment by odlp** [comment]
The `jruby` builds are now passing with a more modern version (`2.x` MRI compatible).

The `rbx` builds are still failing...

**Comment by odlp** [comment]
@alindeman do you have a view on whether testing against `rbx` in CI is still required?

**Comment by alindeman** [comment]
> @alindeman do you have a view on whether testing against rbx in CI is still required?

This overall LGTM, thanks for doing it. I think it's OK to let rbx fail at this point. Could you make that change? I'll merge it afterward.

**Comment by odlp** [comment]
@alindeman updated, thanks!

**Comment by alindeman** [comment]
Super, thanks for your contribution!

**Pull request merged**
